BookEvent/Controllers/BookReadingEventController.cs
using BookEvent.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookEvent.Repository;

namespace BookEvent.Controllers
{
    public class BookReadingEventController : Controller
    {

        private readonly EventRepository _Event = null;
        private readonly EventTypeRepository _EventType = null;

        public BookReadingEventController(EventRepository eventRepo,EventTypeRepository eventType)
        {
            _Event =eventRepo;
            _EventType = eventType;
        }
        

        public ActionResult Invited()
        {
            return View();
        }

        
        // GET: BookReadingEvent
        
        public async Task<ActionResult> Index(int m)
        {
            if (TempData["doc"] ==null)
            {

                
                return RedirectToAction("LogIn", "Home");
            }
            ViewBag.M = TempData["doc"];
            var d = await _Event.TotalEvent();
            return View(d);
        }


       
        // GET: BookReadingEvent/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }
            
            var b = await _Event.ViewDetails(id);
            ViewBag.ETVal = await _EventType.getEventTypeValue(b.Type);
            return View(b);
        }

        public async Task<ActionResult> Myevent(string id)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }
           
            var b = await _Event.Myevent(id);
            return View(b);
        }

        public async Task<ActionResult> EventInvitedTo(string id)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }

            var b = await _Event.EventInvitedTo(id);
            return View(b);
        }


        // GET: BookReadingEvent/Create
        public async Task<IActionResult> Create(bool isSuccces = false,int EventID=0)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }

            ViewData["Title"] = "Create Book";
            ViewBag.IsSuccces = isSuccces;
            ViewBag.EventID = EventID;
            ViewBag.EventType = new SelectList(await _EventType.getEventType(), "ID", "text");
            return View();
        }

        // POST: BookReadingEvent/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookEventModel bookEventModel)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }

            if (ModelState.IsValid)
            {
                int id = await _Event.create(bookEventModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(Create), new { isSuccces = true ,EventID=id});
                }
            }
            ViewBag.EventType = new SelectList(await _EventType.getEventType(),"ID","text");
            ModelState.AddModelError("", "this is my custome error");
            return View();
            
            
        }

        // GET: BookReadingEvent/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }
            
            var b = await _Event.ViewDetails(id);
            ViewBag.EventType = new SelectList(await _EventType.getEventType(), "ID", "text");
            ViewBag.ET = await _EventType.getEventTypeValue(b.Type);
            TempData["k"] = id;
            return View(b);
        }

        // POST: BookReadingEvent/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookEventModel bookEventModel)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }

            if (ModelState.IsValid)
            {
                int i= (int)TempData["k"];
                
                var b = await _Event.ViewDetails(i);
                bookEventModel.EventId = b.EventId;
                //bookEventModel.Type = b.Type;
                ViewBag.ET = await _EventType.getEventTypeValue(bookEventModel.Type);
                int id = await _Event.Edit(bookEventModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(SuccessfullyEdited), new { isSuccces = true, EventID = id });
                }
            }
            
            ViewBag.EventType = new SelectList(await _EventType.getEventType(), "ID", "text");
            ModelState.AddModelError("", "this is my custome error");
            return View();
        }


        public async Task<IActionResult> SuccessfullyEdited(bool isSuccces = false, int EventID = 0)
        {
            if (TempData["doc"] == null)
            {
                return RedirectToAction("LogIn", "Home");
            }

            ViewData["Title"] = "Successfully Edited";
            ViewBag.IsSuccces = isSuccces;
            ViewBag.EventID = EventID;
            ViewBag.EventType = new SelectList(await _EventType.getEventType(), "ID", "text");
            return View();
        }


        // GET: BookReadingEvent/Delete/5
       

       
    }
}

BookEvent/Views/BookReadingEvent/Create.cshtml
@model BookEventModel

@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}

<div class="container">
    <h4 class="display-4"> Create Event</h4>
    <hr />
    @if (ViewBag.IsSuccces == true)
    {
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> You are Sucessfully added a new Book.<br />
            click <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@ViewBag.EventID">Here</a>To view the result
        </div>
    }
    <div class="row">
        <div class="col-md-4">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" value="@TempData["Id"]" readonly/>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartTime" class="control-label"></label>
                    <input asp-for="StartTime" class="form-control" />
                    <span asp-validation-for="StartTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" class="form-control" asp-items="ViewBag.EventType">
                        <option>Select</option>
                    </select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Duration" class="control-label"></label>
                    <input asp-for="Duration" class="form-control" />
                    <span asp-validation-for="Duration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OtherDetails" class="control-label"></label>
                    <input asp-for="OtherDetails" class="form-control" />
                    <span asp-validation-for="OtherDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="InviteByEmail" class="control-label"></label>
                    <input asp-for="InviteByEmail" class="form-control" />
                    <span asp-validation-for="InviteByEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Count" class="control-label"></label>
                    <input asp-for="Count" class="form-control" />
                    <span asp-validation-for="Count" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CommentAdded" class="control-label"></label>
                    <input asp-for="CommentAdded" class="form-control" />
                    <span asp-validation-for="CommentAdded" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BookEvent/Views/BookReadingEvent/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "View Details";
}

@model BookEvent.Models.BookEventModel


<div class="Container">
<h1 class="text-center">View Details</h1>
<br />

<div class="flex-xl-grow-1">
    <table class="table ">

        <thead>
            <tr>
                <th scope="col">UserId</th>
                <th scope="col">Title</th>
                <th scope="col">StartTime</th>
                <th scope="col">Date</th>
                <th scope="col">Duration</th>
                <th scope="col">CommentAdded</th>
                <th scope="col">Count</th>
                <th scope="col">Location</th>
                <th scope="col">Type</th>
                <th scope="col">OtherDetails</th>
                <th scope="col">Description</th>
                <th scope="col">InviteByEmail</th>

            </tr>
        </thead>
        <tbody>

            <tr>
                <th scope="row">@Model.UserId</th>
                <td>@Model.Title</td>
                <td>@Model.StartTime</td>
                <td>@Model.Date</td>
                <td>@Model.Duration</td>
                <td>@Model.CommentAdded</td>
                <td>@Model.Count</td>
                <td>@Model.Location</td>
                <td>@Model.Type</td>
                <td>@Model.OtherDetails</td>
                <td>@Model.Description</td>
                <td>@Model.InviteByEmail</td>


            </tr>


        </tbody>

    </table>

</div>
</div>

BookEvent/Views/BookReadingEvent/Edit.cshtml
@model BookEventModel

@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}
@{
    ViewData["Title"] = "Edit Event";
}


<div class="container">
    <h4 class="display-4"> Edit Event</h4>
    <hr />
    @if (ViewBag.IsSuccces == true)
    {
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> You are Sucessfully Edited.<br />
            click <a asp-controller="BookReadingEvent" asp-action="Create" asp-route-id="@ViewBag.EventID">Here</a>To view the result
        </div>
    }
    <div class="row">
        <div class="col-md-4">
            <form method="post" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" value="@TempData["Id"]" readonly />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartTime" class="control-label"></label>
                    <input asp-for="StartTime" class="form-control" />
                    <span asp-validation-for="StartTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" class="form-control" asp-items="ViewBag.EventType">
                        
                    </select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Duration" class="control-label"></label>
                    <input asp-for="Duration" class="form-control" />
                    <span asp-validation-for="Duration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OtherDetails" class="control-label"></label>
                    <input asp-for="OtherDetails" class="form-control" />
                    <span asp-validation-for="OtherDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="InviteByEmail" class="control-label"></label>
                    <input asp-for="InviteByEmail" class="form-control" />
                    <span asp-validation-for="InviteByEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Count" class="control-label"></label>
                    <input asp-for="Count" class="form-control" />
                    <span asp-validation-for="Count" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CommentAdded" class="control-label"></label>
                    <input asp-for="CommentAdded" class="form-control" />
                    <span asp-validation-for="CommentAdded" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BookEvent/Views/BookReadingEvent/EventInvitedTo.cshtml
@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Event Invition";
}



@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}


@model IEnumerable<BookEvent.Models.BookEventModel>



<div class="Container">
    <h1 class="text-center">Welcome To Events Invited To</h1>
    <br />
    <h1>UpComing Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date > DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>


    <h1>Past Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date < DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>

</div>

BookEvent/Views/BookReadingEvent/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Home Page";
}



@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}

@model IEnumerable<BookEvent.Models.BookEventModel>


<div class="Container">
    <h1 class="text-center">Home Page</h1>
    <br />
    <h1>UpComing Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date > DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>


    <h1>Past Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date < DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>

</div>

BookEvent/Views/BookReadingEvent/Myevent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "My Event";
}



@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}


@model IEnumerable<BookEvent.Models.BookEventModel>

<div class="Container">
    <h1 class="text-center">Welcome To My Events</h1>
    <br />
    <h1>UpComing Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date > DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>
                                <a asp-controller="BookReadingEvent" asp-action="Edit" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">Edit Event</a>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>


    <h1>Past Events Event</h1>
    <br />
    <div class="flex-xl-grow-1">
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th scope="col">EventID</th>
                    <th scope="col">View Details</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    if (@b.Date < DateTime.Now)
                    {
                        <tr>
                            <th scope="row">@b.EventId</th>
                            <td>
                                <div class="btn-group">
                                    <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@b.EventId" class="btn-btn-outline-secondry">View details</a>
                                </div>
                            </td>
                            <td>@b.Title</td>
                            <td>@b.Description</td>
                        </tr>

                    }

                }
            </tbody>

        </table>

    </div>

</div>

BookEvent/Views/BookReadingEvent/SuccessfullyEdited.cshtml
@{
    ViewData["Title"] = "Edit Event";
}



@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}




<div class="container">
    <h4 class="display-4"> Edited Event</h4>
    <hr />
    @if (ViewBag.IsSuccces == true)
    {
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> You are Sucessfully Edited.<br />
            click <a asp-controller="BookReadingEvent" asp-action="Details" asp-route-id="@ViewBag.EventID">Here</a>To view the result
        </div>
    }
</div>

BookEvent/Views/BookReadingEvent/_Layout.cshtml
@{
    TempData.Keep("Id");
    TempData.Keep("doc");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookEvent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookEvent</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookReadingEvent" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookReadingEvent" asp-action="Create"  >Create Book Event</a>
                        </li>

                        

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookReadingEvent" asp-action="Myevent" asp-route-id="@TempData["Id"]">My Event</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookReadingEvent" asp-action="EventInvitedTo" asp-route-id="@TempData["doc"]">Invited To Me</a>
                        </li>

                    </ul>


                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookEvent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>