ConsoleToweb/ConsoleToweb/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace ConsoleToweb.Models
{

    public class BookModel
    {
        [DataType(DataType.DateTime)]
        [Display(Name ="Date and Time")]
        public string MyFeild { get; set; }
        public int Id { get; set; }

        [StringLength(100,MinimumLength =5)]
        [Required(ErrorMessage ="Please Enter the Titel")]

        public string Title { get; set; }

        [Required]
        public string Author { get; set; }

        [Required]
        public string Description { get; set; }

        public string Category { get; set; }
        public string Laungage { get; set; }

       
        [Required]
        [Display(Name = "Total Pages")]
        public int ? TotalPages { get; set; }
        
    }
}

ConsoleToweb/ConsoleToweb/Models/LaungageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleToweb.Models
{
    public class LaungageModel
    {
        public int id { get; set; }
        public string text { get; set; }
    }
}

ConsoleToweb/ConsoleToweb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConsoleToweb.Models;
using System.Dynamic;
namespace ConsoleToweb.Controllers
{
    public class  HomeController : Controller
    {
        [ViewData]
        public string Title { get; set; }
        public IActionResult Index()
        {
            //learn About ViewBag--->
            /*
            ViewBag.t = 123;
            dynamic data = new ExpandoObject();
            data.Id = 1;
            data.name = "Viewdata Name";
            ViewBag.Data = data;
            ViewBag.Type = new BookModel() { Id = 234, Title = "Viewbag Title" };
            */
            Title = "Home Page";
            return View();
        }

        public IActionResult Privacy()
        {

            return View();
        }

        public ViewResult ContactUs()
        {
            // var d = new { id = 1, Title = "pk univar" };
            Title = "Contact";
            return View();
        }

        public ViewResult Temp()
        {
            return View("~/TempView/pkview.cshtml");
        }

        public ViewResult aboutUs ()
        {
            Title = "About Us";
            return View();
        }
    }
}

ConsoleToweb/ConsoleToweb/Controllers/bookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConsoleToweb.Repository;
using ConsoleToweb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ConsoleToweb.Controllers
{
    public class bookController : Controller
    {
        private readonly BookRepository _book = null;

        [ViewData]
        public string Title { get; set; }
        public bookController(BookRepository bookRepository)
        {
            _book = bookRepository;
        }
        public async Task<IActionResult> getAllbook()
        {
            Title = "Get All Book";
            var data= await _book.GetAllBook() ;
            return View(data);
        }
       //[Route("book-details/{id}")]

        public async Task<IActionResult> getBookbyId(int id)
        {
            Title = "GetBookByID";
            var d = await _book.GetBookbyID(id);
            return View(d);
        }

        public List<BookModel> SearchBook(string Author, string Title)
        {
            return _book.SearchBook(Author,Title);
        }

                
        public IActionResult AddNewBOOK(bool isSuccces = false,int bookID=0)
        {
            var model = new BookModel() { Laungage="2" };
            ViewBag.IsSuccces = isSuccces;
            ViewBag.BookID = bookID;
            ViewBag.Launagage = new SelectList(getLaungage(), "id", "text");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBOOK(BookModel bookModel)
        {
            if(ModelState.IsValid)
            {
                int id = await _book.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBOOK), new { isSuccces = true, bookID = id });
                }
            }
            ViewBag.Launagage =new SelectList( getLaungage(),"id","text");
            ModelState.AddModelError("", "this is my custome error");
            
            return View();
            
        }

        public List<LaungageModel> getLaungage()
        {
            return new List<LaungageModel>
            {
                new LaungageModel(){id = 1, text = "Hindi" },
                new LaungageModel(){id = 2, text = "English" },
                new LaungageModel(){id = 3, text = "German" },
            };
        }

    }
}

ConsoleToweb/ConsoleToweb/Views/book/AddNewBook.cshtml
@{
    ViewData["Title"] = "AddNewBook";
}

@model BookModel

<div class="container">
    <h1 class="display-4">Add New Book</h1>
    <hr />
    @if (ViewBag.IsSuccces == true)
    {
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> You are Sucessfully added a new Book.<br />
            click <a asp-controller="book" asp-action="getBookbyId" asp-route-id="@ViewBag.BookID">Here</a>To view the result
        </div>
    }


<form method="post" asp-action="AddNewBook" asp-controller="book">
    <div asp-validation-summary="None" class="text-danger"></div>

    <div class="form-group">
        <lable asp-for="MyFeild" class="control-label">MyFeild<span>*</span></lable>
        <input asp-for="MyFeild" class="form-control" />
        <span asp-validation-for="MyFeild" class="text-danger"></span>
    </div>

    <div class="form-group">
        <lable asp-for="Title" class="control-label">Title<span>*</span></lable>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <lable>Author*</lable>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <lable asp-for="TotalPages" class="control-label">TotalPages*</lable>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

    <div class="form-group">
        <lable>Description*</lable>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <lable asp-for="Laungage" class="control-label">Laungage</lable>
        <select asp-for="Laungage" class="=form-control" asp-items="ViewBag.Launagage" required>
           <option value="">Please select your Laungage</option>
        </select>
        <span asp-validation-for="Laungage" class="text-danger"></span>

    </div>

    <div class="form-group">
        <input type="submit" value="add Book" class="btn btn-primary" />

    </div>

</form>
</div>

        

ConsoleToweb/ConsoleToweb/Views/book/getAllbook.cshtml
@*@{
        ViewData["Title"] = "Get All Book";
    }*@

@*@{
    ViewData["Title"] = "Contact Us";
*@

<div class="text-md-center">
    <h1>Get All Books</h1>
</div>
<div class="container">
    <h3> All Books</h3>
    <div class="row">
        @foreach (var b in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%"
                              height="100%" fill="#55595c" />
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">@b.Title</text>
                    </svg>
                    <div class="card-body">
                        <h3 class="card-title">@b.Title</h3>
                        <p class="card-text">@b.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a asp-controller="book" asp-action="getBookbyId" asp-route-id="@b.Id" class="btn-btn-outline-secondry">View details</a>
                            </div>
                            <small class="text-muted">@b.Author</small>

                        </div>
                    </div>
                </div>
            </div>
         }
    </div>
</div>

ConsoleToweb/ConsoleToweb/Views/book/getBookbyId.cshtml
@*@{
        ViewData["Title"] = "Book Details "+ Model.Title;
    }*@

@* model BookModel;*@



<div class="container">

    <div class="row">

        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="~/images/Book/book1.jpg" class="d-block w-100" alt="First Slide" height="305" width="250">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/Book/book2.jpg" class="d-block w-100" alt="Second Slide" height="305" width="250">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/Book/book3.jpg" class="d-block w-100" alt="Third Slide" height="305" width="250">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                <div class="col-md-12">
                    <h1>@Model.Title </h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="col-form-label">By: </span>
                    <span class="font-monospace">@Model.Author></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <button class="btn btn-outline-primary">
                        Read Now
                    </button>
                </div>
            </div>

            <hr />
            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold"> Category =</span>@Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold"> Total pages=</span>@Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold"> Laungage=</span>@Model.Laungage</li>
            </ul>

        </div>
        <hr />
        <div class="py-5 bg-light">
            <h3 class="h3">Similer book</h3>
            <div class="row">
                @for (int i = 0; i < 5; i++)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                                <title>Placeholder</title>
                                <rect width="100%"
                                      height="100%" fill="#55595c" />
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em">@Model.Title</text>
                            </svg>
                            <div class="card-body">
                                <h3 class="card-title">@Model.Title</h3>
                                <p class="card-text">@Model.Description</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="/book/getBookbyId/@Model.Id" class="btn-btn-outline-secondry">View details</a>
                                    </div>
                                    <small class="text-muted">@Model.Author</small>

                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>